    ---
deployment:
  tasks:
    - export DEPLOYPATH=/home/timwinne/public_html/
    - export REPOPATH=/home/timwinne/repositories/personal-site-HTML-CSS-2
    - /bin/rm -Rf ${DEPLOYPATH}_old
    - /bin/cp -R ${DEPLOYPATH} ${DEPLOYPATH}_old
    - /bin/rsync -a --exclude '.git' --exclude '.well-known' ${REPOPATH}/ ${DEPLOYPATH} --delete-after
    - /bin/chmod 755 ${DEPLOYPATH}
    - /bin/find ${DEPLOYPATH} -type d -exec /bin/chmod 755 '{}' \;
    - /bin/find ${DEPLOYPATH} -type f -exec /bin/chmod 644 '{}' \;